package com.xworkz.encapsulationone;

import com.xworkz.encapsulationone.data.ShopDto;

public class ShopDtoRunner {

	public static void main(String[] args) {
		ShopDto obj	= new ShopDto("shopandshop", "sham", 7799, "btm layout", 876, 585103, "lays", "nandini", "nandini", 10, 12, 49, "moms magic", 10, 65777, 68688, 78768, "carrot", 123, 's', 9876, true);
		
	
	obj.setNameOfTheShop("shopandshop");
	obj.setOwner("sham");
	obj.setNoOfItems(7799);
	obj.setAddress("btm layout");
	obj.setPriceOfTheShop(876);
	obj.setPincode(585103);
	obj.setChips("lays");
	obj.setCurd("nandini");
	obj.setMilk("nandini");
	obj.setPriceChips(87);
	obj.setPriceCurd(76);
	obj.setPriceMilk(87);
	obj.setBiscuit("britania");
	obj.setBiscuitPrice(876);
	obj.setDailyIncome(98765);
	obj.setDailyLoss(87);
	obj.setDailyExpenditure(8765);
	obj.setVegetable("beans");
	obj.setVegetablePrice(876);
	obj.setFirstLetterOfTheShopName('S');
	obj.setPriceVegetable(76);
	//obj.setIsShopIsGood(true);
	obj.setEnergyDrink("protein");
	obj.setProteinPowder("proteinex");
	obj.setEnergyDrinkPrice(1000);
	obj.setNoOfUnUseItems(890);
	obj.setUsableItem(899);
	obj.setFruits("mango");
	obj.setFruitsPrice(120);
	obj.setMostExpensiveItem(1000);
	obj.setCheapItem(1200);
	obj.setHorlicsPrice(3000);
	obj.setBoostPrice(100);
	obj.setBreadPrice(3400);
	obj.setCheesePrice(500);
	obj.setPaneerPrice(300);
	obj.setCheeseSlicePrice(890);
	obj.setShampooo("meera");
	obj.setShampoooPrice(700);
	obj.setSoap("santoor");
	obj.setSoapPrice(800);
	obj.setPaste("danta kanti");
	obj.setPastePrice(20000);
	obj.setNoOfBiscuit(10000);
	obj.setNoOfShampooProduct(800);
	obj.setLowestPriceBiscuit(20000);
	obj.setHighestPriceBiscuit(10000);
	obj.setToastPrice(500);
	obj.setToast("shark");
	obj.setJam("kissan");
	obj.setJamPrice(765);
	obj.setSauce("kissan");
	obj.setSaucePrice(120);
	obj.setOnionPrice(3456);
	obj.setTomatoPrice(900);
	obj.setChilliPrice(765);
	obj.setApplePrice(678);
	obj.setGauvaPrice(789);
	obj.setPineApplePrice(890);
	obj.setBananaPrice(9090);
	obj.setMangoPrice(9096);
	obj.setPotatoPrice(9098);
	obj.setCucumberPrice(9091);
	obj.setCarrotPrice(9094);
	obj.setLadyFingerPrice(9094);
	obj.setBeansPrice(9094);
	
	
	System.out.println(obj.getNameOfTheShop());
	System.out.println(obj.getOwner());
	System.out.println(obj.getNoOfItems());
	System.out.println(obj.getAddress());
	System.out.println(obj.getPriceOfTheShop());
	System.out.println(obj.getPincode());
	System.out.println(obj.getChips());
	System.out.println(obj.getCurd());
	System.out.println(obj.getMilk());
	System.out.println(obj.getPriceChips());
	System.out.println(obj.getPriceCurd());
	System.out.println(obj.getPriceMilk());
	System.out.println(obj.getBiscuit());
	System.out.println(obj.getBiscuitPrice());
	System.out.println(obj.getDailyIncome());
	System.out.println(obj.getDailyLoss());
	System.out.println(obj.getDailyExpenditure());
	System.out.println(obj.getVegetable());
	System.out.println(obj.getVegetablePrice());
	System.out.println(obj.getFirstLetterOfTheShopName());
	System.out.println(obj.getEnergyDrink());
	System.out.println(obj.getProteinPowder());
	System.out.println(obj.getEnergyDrinkPrice());
	System.out.println(obj.getNoOfUnUseItems());
	System.out.println(obj.getUsableItem());
	System.out.println(obj.getFruits());
	System.out.println(obj.getFruitsPrice());
	System.out.println(obj.getMostExpensiveItem());
	System.out.println(obj.getCheapItem());
	System.out.println(obj.getHorlicsPrice());
	System.out.println(obj.getBoostPrice());
	System.out.println(obj.getBreadPrice());
	System.out.println(obj.getCheesePrice());
	System.out.println(obj.getPaneerPrice());
	System.out.println(obj.getCheeseSlicePrice());
	System.out.println(obj.getShampooo());
	System.out.println(obj.getShampoooPrice());
	System.out.println(obj.getSoap());
	System.out.println(obj.getSoapPrice());
	System.out.println(obj.getPaste());
	System.out.println(obj.getPastePrice());
	System.out.println(obj.getNoOfBiscuit());
	System.out.println(obj.getNoOfShampooProduct());
	System.out.println(obj.getLowestPriceBiscuit());
	System.out.println(obj.getHighestPriceBiscuit());
	System.out.println(obj.getToastPrice());
	System.out.println(obj.getToast());
	System.out.println(obj.getJam());
	System.out.println(obj.getJamPrice());
	System.out.println(obj.getSauce());
	System.out.println(obj.getSaucePrice());
	System.out.println(obj.getOnionPrice());
	System.out.println(obj.getTomatoPrice());
	System.out.println(obj.getChilliPrice());
	System.out.println(obj.getApplePrice());
	System.out.println(obj.getGauvaPrice());
	System.out.println(obj.getPineApplePrice());
	System.out.println(obj.getBananaPrice());
	System.out.println(obj.getMangoPrice());
	System.out.println(obj.getPotatoPrice());
	System.out.println(obj.getCucumberPrice());
	System.out.println(obj.getCarrotPrice());
	System.out.println(obj.getLadyFingerPrice());
	System.out.println(obj.getBeansPrice());

   }
}